apiVersion: apps/v1
kind: Deployment
metadata:
  name: historiasclinicasfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: historiasclinicasfrontend
  template:
    metadata:
      labels:
        app: historiasclinicasfrontend
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: historiasclinicasfrontend
        image: localhost:5000/historiasclinicasfrontend:latest  # Cambia esto según tu registro
        ports:
        - containerPort: 4201
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: historiasclinicasfrontend
spec:
  type: ClusterIP
  selector:
    app: historiasclinicasfrontend
  ports:
    - name: http
      protocol: TCP
      port: 4201
      targetPort: 4201
