export interface ReporteMovi {
    tsolicitudId?: number, 
    ttiposolicitudId?: number,
    tusuasoli?: string,
    tdescusuasoli?: string,
    tdescpues?: string,
    tnombunidfunc?: string,
    tfechresp?: string,
    tusuaaprob?: string,
    tdescusuaaprob?: string,
    tfechactu?: string,
    tusuaactu?: string,
    tdesctiposolicitud?: string,
    tstatus?: number,
    statusDesc?: string,
    tmonto?: number,
    tfechinicsoli?: string,
    tfechfinasoli?: string,
    tnumeviaje?: number
}